---
title: Introduction
---

In this document, I present a spatial sorting model that elucidates the dynamics of interactions between heterogeneous workers and firms. Within this framework, workers exhibit varying skills, while firms exhibit varying levels of productivity. These diverse actors engage in a frictional labor market, where the productivity of workers is contingent upon the skill distribution within their respective locations, a phenomenon commonly referred to as the agglomeration effect.

A fundamental aspect of my research revolves around the exploration of workers' search behavior. Diverging from conventional models, wokers can "partially" direct their search  to specific locations by employing a mixed strategy. This strategy emerges as the optimal as the soltion of the maximization problem of economic agents who weigh the costs associated with acquiring and processing information against their cognitive constraints (this assumption is commonly reffered to as *rational inattention* [@simsImplicationsRationalInattention2003] and [@simsRationalInattentionLinearQuadratic2006]). The optimal strategy assigns a positive probability to all available locations, with the probability increasing in proportion to the worker's anticipated surplus in each locale. The outcomes generated by this approach are consistent with those obtained using a discrete choice framework, as demonstrated in [@lentzCompetitiveRandomSearch].

Furthermore, I model agglomeration effects as a function of the skill distribution within each location. Borrowing insights from [@davisSpatialKnowledgeEconomy2019], I assume that workers derive benefits from interacting with one another, with a greater emphasis on the advantages gained from interacting with skilled workers.

In this document I lay out the ingredients of the model. I do not present the equilibrium, nor do I discuss the solution method. 