primitives:
  c     : 1.0       # Cost of search for workers
  beta  : 0.952381  # Discount factor (consisten with 5% annual discount rate)
  delta : 0.012     # Probability of match destruction 
  s     : 0.027     # Search intensity employed workers
  # Cost of living parameters
  theta : 0.04       # TODO
  gamma : 0.1       # Curvature of cost of living function
  # Production function parameters
  A     : 1         # Gains from idea exchange
  alpha : 0.5       # Worker share
  nu    : 10        # Idea exchange parameter
  b_hat : 0.7       # Home production parameter
  # Vacancy creation cost function
  c_0   : 0.028     # 
  c_1   : 0.584     # 
  # Matching function
  omega_1 : 0.0497  
  omega_2 : 0.5
  # Cost of moving location
  F_bar   : 1.0     # Fixed cost of moving

grids:
  n_x : 21          # Number of skills levels workers
  n_y : 20          # Number of prductivity levels firms
  n_j : 10          # Number of locations  
  n_z : 51          # Number of aggregate productivity levels
  x_min  : 0.0      # Minimum skill level
  x_max  : 1.0      # Maximum skill level
  y_min  : 0.0      # Minimum productivity level
  y_max  : 1.0      # Maximum productivity level

