---
title: Introduction
---
*Notes*:

- I adopt the framework from [@liseMacrodynamicsSortingWorkers2017].
- Introducing a fixed amount of locations and population distribution of workers should be an equilibrium outcome.
- Workers can "partially" direct their search to each location.
  - In practice workers randomize over locations paying a cost.
  - Cost of random search is zero.
  - Cost increases unboundedly as the worker directs their search to a particular location.
- Productivity depends on the quality of match and aggregate state as in the original paper. I want to introduce a third component which is location productivity. 
  - I intend to use idea exchange as the driver of location productivity.
  - I plan to draw on a framework similar to [@davisSpatialKnowledgeEconomy2019] to model the value added to production by idea exchange.

## **TODO**:

- [ ] Read [@simsImplicationsRationalInattention2003]
- [ ] Read [@matejkaRationalInattentionDiscrete2015]
- [ ] Check that the unemployment value function is a contraction.
- [ ] Think about distribution of firms across and within locations.
- [ ] For now the cost of posting only depends on the number of vacancies, should I introduce a location component? I think It will be important to have only high productive firms posting a lot of vacancies in high productivity locations.

**From Rasmus meeting**:

- [ ] Talk to John Keenan
- [ ] Figure out a way to talk to Espen R. Moen he is visiting in October.
- [ ] Read [@cahucWageBargainingOntheJob2006]
- [ ] Read [@baggerEmpiricalModelWage2019]
- [ ] I could drop the extreme bargaining assumption If I'm not going to compute transitional dynamics.

**From Carter meeting**:

- [ ] Read [@liseMultidimensionalSkillsSorting2020]