---
format:
  pdf:
    colorlinks: true
    keep-tex: true
    reference-section-title: "References"
    render-on-save: true
    latex-auto-mk : true
    link-citations: true

bibliography: /Users/mitchv34/Work/Labor_Market Search_Sorting.bib
  
---

# Model Setup

Everithing is the same as in the main document.

# Bellman Equations

## Worker

$$\begin{align*}
U^{j}_{t}(x) = \underbrace{b(x,j,z_t)}_{\text{instant utility}} + &\beta\max_{\phi^j_u(x)}\left\{ \underbrace{-c(\phi^j_u(x))}_{\text{cost of search strategy}} \right.  + \\
& \mathbb{E}_{t}\sum_{j'\in \mathcal{J}} \underbrace{\phi^j_u(x, j')}_{\text{weight by probability of search in} j'}\left[ \overbrace{(1-p^{j'}_{t+1})U^{j'}_{t+1}(x)}^{\text{no offer, stays unemployed now in} j'} \right.  \\
& \left. \left. \hspace{0cm} + p^{j'}_{t+1} \underbrace{\int \max\left\{U^{j'}_{t+1}(x),W^{j\to j'}_{0, t+1}(x,y)\right\}\frac{v^{j'}_{t+1}(y)}{V^{j'}_{t+1}}dy}_{\text{if offer, pays cost,moves to } j \text{ and then is matched randomly with some firm}} \right] \right\} 
\end{align*}$$

## Value of a match

$$\begin{align*}
J^j_t(x,y) = \underbrace{f(x,y,j,z_t)}_{\text{match value added}} &+ \beta\mathbb{E}_t\left[  \overbrace{ (1-\lambda^j_{t+1}(x,y)) }^{\text{match is destroyed}}\underbrace{U^{j}_{t+1}(x)}_{\text{worker gets unemployment value}} \right. + \\
  & \underbrace{(\lambda^j_t(x,y)}_{\text{match survives}} \max_{\phi_s^j(x)}\left\{-c(\phi_s^j(x)) +  \sum_{j'\in\mathcal{J}}\phi^j_s(x,j')\left[ \overbrace{(1-sp^{j'}_t)}^{\text{no new offers}} \underbrace{J^j_{t+1}(x,y)}_{\text{stays with same firm}} \right. \right. +\\
& sp^{j'}_t \left. \underbrace{\int\max\{J^{j}_{t+1}(x,y),W^{j\to j'}_{1,t+1}(x,y',y)\}\frac{v^{j'}_{t+1}(x)}{V^{j'}_{t+1}}dy'}_{\text{worker only accepts new offers if value is greater than current match}}  \right]
\end{align*}$$
## Surplus of a Match
$$S^{j\to j'}(x,y) = J^{j'}(x,y) - \left[U^j(x) + F^{j\to j'}\right]$$
# Bargaining

I use the same bargaining as in [@cahucWageBargainingOntheJob2006] this have the following implications for the value that a worker gets from a match:

- Unemployed worker in location $j$ when matched with firm $y$ in location $j'$ gets: $$W^{j \to j'}_{0}(x,y) = (1 - \mu) U^{j'}(x) + \mu [J^{j'}(x,y) - F^{j' \to j}] = U^{j}(x) + \mu \left(J^{j'}(x,y) - [U^{j}(x) + F^{j' \to j}]\right)$$
- Worker employed in location $j$ by firm $y$ when matched with firm $y'$ in location $j'$ gets: $$W^{j \to j'}_{1}(x,y) = (1 - \mu) J^{j}(x,y) + \mu [J^{j'}(x,y') - F^{j' \to j}] = J^{j}(x,y) + \mu \left(J^{j'}(x,y') - J^{j}(x,y) - F^{j' \to j}\right)$$

Plugging this into the Bellman equations we get:

## Worker
$$\begin{align*}
U^{j}_{t}(x) &= b(x,j,z_t) + \beta\max_{\phi^j_u(x)}\left\{ -c(\phi^j_u(x))    + \mathbb{E}_{t}\sum_{j'\in \mathcal{J}} \phi^j_u(x, j')\left[ (1-p^{j'}_{t+1})U^{j'}_{t+1}(x) \right. \right.  \\
& \left. \left. \hspace{3cm} + p^{j'}_{t+1} \int \max\left\{U^{j'}_{t+1}(x),U_{t+1}^{j}(x) + \mu \left(J_{t+1}^{j'}(x,y) - [U_{t+1}^{j}(x) + F^{j' \to j}]\right)\right\}\frac{v^{j'}_{t+1}(y)}{V^{j'}_{t+1}}dy \right] \right\} \\
&= b(x,j,z_t) + \beta\max_{\phi^j_u(x)}\left\{ -c(\phi^j_u(x))  +   \mathbb{E}_{t}\sum_{j'\in \mathcal{J}} \phi^j_u(x, j')\left[ (1-p^{j'}_{t+1})U^{j'}_{t+1}(x) + p^{j'}_{t+1}U^{j'}_{t+1}(x)\right. \right.  \\
& \left. \left. \hspace{3cm} + p^{j'}_{t+1} \mu \int \max\left\{0, J_{t+1}^{j'}(x,y) - [U_{t+1}^{j}(x) + F^{j' \to j}] \right\}\frac{v^{j'}_{t+1}(y)}{V^{j'}_{t+1}}dy \right] \right\} \\
&= b(x,j,z_t) + \beta\mathbb{E}_{t+1}\left[U^j_{t+1}(x)\right] + \beta\left( \sum_{j'\in\mathcal{J}}\phi^{j}_{u}(x,j')\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, J_{t+1}^{j'}(x,y) - [U_{t+1}^{j}(x) + F^{j' \to j}] \right\}\frac{v^{j'}_{t+1}(y)}{V^{j'}_{t+1}}dy \right] - c\left(\phi_{u}^{j}(x)\right)\right)
\end{align*}
$$
Recall that the surplus of a match is defined as $$S^{j\to j'}(x,y) = J^{j'}(x,y)-[U^j(x)+F^{j \to j'}]$$
We can rewrite the Bellman equation of the unemployed worker as:
$$U^{j}_{t}(x) = b(x,j,z_t) + \beta\mathbb{E}_{t+1}\left[U^j_{t+1}(x)\right] + \beta\left( \sum_{j'\in\mathcal{J}}\phi^{j}_{u}(x,j')\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to j'}(x,y) \right\}\frac{v^{j'}_{t+1}(y)}{V^{j'}_{t+1}}dy \right] - c\left(\phi_{u}^{j}(x)\right)\right)$$
We can derive the optimal strategy for each worker as:
$$\phi_{u}^{j}(x,j')=\frac{\exp{\left(\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to j'}(x,y) \right\}\frac{v^{j'}_{t+1}(y)}{V^{j'}_{t+1}}dy \right] / c\right)}}{\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{\tilde{j}}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to \tilde{j} }(x,y) \right\}\frac{v^{ \tilde{j} }_{t+1}(y)}{V^{\tilde{j}}_{t+1}}dy \right] / c\right)}}$$
Plug back into the value function to get:
$$U^{j}_{t}(x) = b(x,j,z_t) + \beta\left[\mathbb{E}_{t+1}\left[U^j_{t+1}(x)\right]  + c\log\left({\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to j' }(x,y) \right\}\frac{v^{ j' }_{t+1}(y)}{V^{j'}_{t+1}}dy \right] / c\right)}} + c\log(\mid \mathcal{J} \mid ) \right)\right]$$

## Value of a match

$$\begin{align*}
J^j_t(x,y) &= {f(x,y,j,z_t)} + \beta\mathbb{E}_t\left[   (1-\lambda^j_{t+1}(x,y))U^{j}_{t+1}(x) \right.  + \lambda^j_t(x,y)\max_{\phi_s^j(x)}\left\{-c(\phi_s^j(x)) +  \sum_{j'\in\mathcal{J}}\phi^j_s(x,j')\left[ (1-sp^{j'}_t) J^j_{t+1}(x,y) \right. \right. +\\ 
& \hspace{7cm}sp^{j'}_t \left.\int\max\{J^{j}_{t+1}(x,y), J^{j}(x,y) + \mu \left(J^{j'}(x,y') - J^{j}(x,y) - F^{j' \to j}\right)\}\frac{v^{j'}_{t+1}(x)}{V^{j'}_{t+1}}dy'  \right]\\
&= {f(x,y,j,z_t)} + \beta\mathbb{E}_t\left[   (1-\lambda^j_{t+1}(x,y))U^{j}_{t+1}(x) \right.  +\lambda^j_t(x,y)J^j_{t+1}(x,y) + \\
&\left.\hspace{4.5cm} \lambda^j_t(x,y)\max_{\phi_s^j(x)}\left\{\sum_{j'\in\mathcal{J}}\phi^j_s(x,j') \int\max\{0, J^{j'}(x,y') - J^{j}(x,y) - F^{j' \to j}\}\frac{v^{j'}_{t+1}(x)}{V^{j'}_{t+1}}dy' -c(\phi_s^j(x)) \right\} \right]\\
&= {f(x,y,j,z_t)} + \beta\mathbb{E}_t\left[   (1-\lambda^j_{t+1}(x,y))U^{j}_{t+1}(x) \right.  +\lambda^j_t(x,y)J^j_{t+1}(x,y) + \\
&\left.\hspace{4.5cm} \lambda^j_t(x,y)\max_{\phi_s^j(x)}\left\{\sum_{j'\in\mathcal{J}}\phi^j_s(x,j') \int\max\{0, S^{j\to j'}(x,y') - S^{j\to j}(x,y) \}\frac{v^{j'}_{t+1}(x)}{V^{j'}_{t+1}}dy' -c(\phi_s^j(x)) \right\} \right]
\end{align*}$$
We can derive the optimal strategy for each worker as:
$$\phi_{u}^{j}(x,y,j')=\frac{\exp{\left(\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to j'}(x,y') - S^{j \to j}_{t+1}(x,y) \right\}\frac{v^{j'}_{t+1}(y')}{V^{j'}_{t+1}}dy' \right] / c\right)}}{\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{\tilde{j}}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to \tilde{j} }(x,y')-S^{j \to j}_{t+1}(x,y) \right\}\frac{v^{ \tilde{j} }_{t+1}(y')}{V^{\tilde{j}}_{t+1}}dy' \right] / c\right)}}$$
Plug back into the value function:
$$J^j_t(x,y) = {f(x,y,j,z_t)} + \beta\left[\mathbb{E}_t\left[  (1-\lambda^j_{t+1}(x,y))U^{j}_{t+1}(x)   +\lambda^j_t(x,y)J^j_{t+1}(x,y) \right]+\log\left(\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{\tilde{j}}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to \tilde{j} }(x,y')-S^{j \to j}_{t+1}(x,y) \right\}\frac{v^{ \tilde{j} }_{t+1}(y')}{V^{\tilde{j}}_{t+1}}dy' \right] / c\right)} \right) - c \log(\mid\mathcal{J}\mid)\right]$$
Note that 
$$\begin{align*}
S_t^{j\to j}(x,y) &= J_t^{j}(x,y) - U_t^j(x) \\
&= s(x,y,j,z_t) + \beta\left[ \mathbb{E}_{t}\left[\lambda^{j}(x,y)\left(J_{t+1}^{j}(x,y) - U_{t+1}^j(x)\right)\right]+\log\left(\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{\tilde{j}}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to \tilde{j} }(x,y')-S^{j \to j}_{t+1}(x,y) \right\}\frac{v^{ \tilde{j} }_{t+1}(y')}{V^{\tilde{j}}_{t+1}}dy' \right] / c\right)} \right) -  c\log\left(\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to j' }(x,y) \right\}\frac{v^{ j' }_{t+1}(y)}{V^{j'}_{t+1}}dy \right] / c\right)}\right)\right]\\
&= s(x,y,j,z_t) + \beta\left[ \mathbb{E}_{t}\left[(1-\delta)\max\left(\{0, S_{t+1}^{j\to j}(x,y)\right\}\right]+\log\left(\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{\tilde{j}}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to \tilde{j} }(x,y')-S^{j \to j}_{t+1}(x,y) \right\}\frac{v^{ \tilde{j} }_{t+1}(y')}{V^{\tilde{j}}_{t+1}}dy' \right] / c\right)} \right) -  c\log\left(\sum_{\tilde{j}\in \mathcal{J}}\exp{\left(\mathbb{E}_{t}\left[p^{j'}_{t+1} \mu \int \max\left\{0, S_{t+1}^{j\to j' }(x,y) \right\}\frac{v^{ j' }_{t+1}(y)}{V^{j'}_{t+1}}dy \right] / c\right)}\right)\right]
\end{align*}$$
