## Dynamic Programming Problem

Denote:

-   $U^{j}_t(x)$ the value for an unemployed worker of type $x$ at time $t$ at location $j$.
-   The value of getting an offer depends on whether the worker is employed or not:
    -   $W^{j'\to j}_{0, t}(x,y)$ is the value of a type-$x$ unemployed worker at location $j'$ who is hired by a ﬁrm of type $y$ at a location $j$.
    -   $W^{j'\to j}_{1, t}(x,y,y')$ is the value offered at the time $t$ by type $y$ firm at location $j$ to a type $x$ worker employment at a type $y'$ firm in location $j'$.
-   $J^j_t(x,y)$ is the value of a match between a type $x$ worker and a type $y$ firm at time $t$ in location $j$.

## Unemployed Worker

Unemployed workers receive instant utility from living in location $j$, $b(x,j, z)$, and anticipate next period's aggregate state $z_{t+1}$, and the probability of getting an offer $p^j_{t+1}$ in each location. They will choose the strategy that maximizes their future expected value knowing that in each location they will receive an offer which can be from any firm with a likelihood proportional to the share of total vacancies posted by each firm in each market. The worker will accept only the offers that promise her a higher value than unemployment:

```{=latex}
\begin{align*}
U^{j}_{t}(x) = b(x,j, z) + &\beta\max_{\phi^j_u(x)}\left\{ -c(\phi^j_u(x)) + \phi^j_u(x, j')\mathbb{E}_{t}
      \sum_{j'\in \mathcal{J}} \left[ 
      (1-p^{j'}_{t+1})U^{j'}_{t+1}(x) +\ldots\right. \right. \\
& \left. \left. \hspace{3cm} \ldots + p^{j'}_{t+1} \int \max\left\{U^{j'}_{t+1}(x),W^{j\to j'}_{0, t+1}(x,y)- F^{j \to 
j'}\right\}\frac{v^{j}_{t+1}(y)}{V^{j}_{t+1}}dy \right] \right\} 
\end{align*}
```
Assume that workers don't have bargaining power, therefore they are offered their reservation value $U^{j'}_t(x)=W^{j\to j'}_{0, t+1}(x,y)- F^{j \to j'}$ by firms: $$U^{j}_{t}(x) = b(x, j, z) + \beta \max_{\phi^j_u(x)} \left\{\sum_{j'\in \mathcal{J}} \left(\phi^j_u(x, j')\mathbb{E}_t\left[U^{j'}_{t+1}(x)  \right]\right) -c(\phi^j_u(x)) \right\} $$

This means that the optimal search policy for each worker is $$ \phi^j_u(x,j') = \frac{e^{\left(\mathbb{E}_t\left[U^{j'}_{t+1}(x)\right] /c_1\right)}}{\sum_{\tilde{j}\in \mathcal{J}}e^{\left(\mathbb{E}_t\left[U^{\tilde{j}}_{t+1}(x)\right] /c_1\right)}}$$ {#eq-optimal-search-unemployed}

derivation is in @sec-appendix_search_unemp.

Substituting the optimal strategy into the Bellman Equation of the unemployed worker we get (derivation in @sec-appendix_bellman_unemp): $$U^{j}_{t}(x) = b(x, j, z) + \beta c_1 \log{\left( \sum_{j' \in \mathcal{J}}\exp{\left(\mathbb{E}_t[U_{t+1}^{j'}(x)]/c_1\right)}-\log{(J)}\right)}$$ or simply $$U^{j}_{t}(x)=b(x,j,z)+\beta c_{1}\text{lse}\left(\left\{\frac{\mathbb{E}_{t}[U^{j'}_{t+1}(x)]}{c_{1}}\right\}\right) - \beta c_{1}\log{J}$$ {#eq-bellman-unemployed}

Where $\text{lse}(x\in \mathbb{R}^n)$ is the **log-sum-exp** function.

## Firm

-   If a match between a worker and a firm in location $j$ is destroyed the firm will get $0$ and the worker gets their unemployment value in that location $U^j_t(x)$.
-   Matches are destroyed for two reasons:
    -   *Exogenous destruction* with probability $\delta$
    -   *Endogenous destruction*, if and only if $J^j_t(x,y) < U^j_t(x)$.
        -   Denote $\lambda^j_{t}(x,y) = \mathbb{1}_{\{J^j_{t}(x,y)>U^j_{t}(x,y)\}}$

We can write the Bellman equation of a match value as:

```{=tex}
\begin{align*}
J^j_t(x,y) = \underbrace{f(x,y,j,z_t)}_{\text{match value added}} &+ \beta\max_{\phi^j_s(x)}\left\{\mathbb{E}_t\left[  \overbrace{ (1-(1-\delta)\lambda^j_{t+1}(x,y)) }^{\text{match is destroyed}}\underbrace{U^j_{t+1}(x)}_{\text{worker gets unemployment value}} \right. \right. + \ldots\\
\ldots + & \underbrace{(1-\delta)\lambda^j_t(x,y)}_{\text{match survives}} \max_{\phi_s^j(x)}\left\{-c(\phi_s^j(x)) +  \sum_{j'\in\mathcal{J}}\phi^j_s(x,j')\left[ \overbrace{(1-sp^{j'}_t)}^{\text{no new offers}} \underbrace{J^j_{t+1}(x,y)}_{\text{stays with same firm}} \right. \right. +\ldots\\
&\ldots +sp^{j'}_t \left.\left. \underbrace{\int\max\{J^{j}_{t+1}(x,y),W^{j\to j'}_{1,t+1}(x,y',y)-F^{j\to j'}\}\frac{v^{j'}_{t+1}(x)}{V^{j'}_{t+1}}dy'}_{\text{worker only accepts new offers if value is greater than current match}}  \right] \right\}
\end{align*}
```
When a type $x$ worker employed at a type $y$ firm in city $j$ receives an offer from a type $y'$ in city $j'$ then there is a sequential auction like in [@postel-vinayEquilibriumWageDispersion2002]. More productive firms can offer higher values. The key difference with [@postel-vinayEquilibriumWageDispersion2002] is that location plays a role: if a firm is located in a different location than the worker's current employer then the poaching firm must cover the cost of moving, this leads to two possible outcomes:

-   $J^{j'}_{t+1}(x,y')>J^j_{t+1}(x,y)+F^{j\to j'}$ the worker moves from $(j,y) \to (j',y')$ and receives $W^{j\to j'}_{1,t+1}(x,y',y)$
-   $J^j_{t+1}(x,y)>J^{j'}_{t+1}(x,y')-F^{j\to j'}$ the worker stays at $(j,y)$ and receives $W^{j}_{1,t+1}(x,y,y')$

to able to poach from different locations the firm must be at least $F^{j\to j'}$ more productive.

As in [@postel-vinayEquilibriumWageDispersion2002] if the worker is hired by the poaching firm the worker receives the incumbent firm reservation value plus the cost of changing jobs, i.e.

$$J^{j'}_{t+1}(x,y')>J^{j}_{t+1}(x,y)+F^{j\to j'}  \qquad \implies \qquad W^{j\to j'}_{1,t+1}(x,y',y) = J^{j}_{t+1}(x,y)+F^{j\to j'}$$

therefore

```{=tex}
\begin{align*}
    J^j_{t}(x,y)=f(x,y,j,z_t)+\beta\max_{\phi^j_s(x)}\left\{\mathbb{E}_t\left[(1 - (1-\delta)\lambda^j_{t+1}(x,y))U^j_{t+1}(x) \right.\right. \\ \left.\left. + (1-\delta) \lambda^j_t(x,y)\sum_{j'\in\mathcal{J}}\phi_s^j(x,j')J^j_{t+1}(x,y)\right] - c(\phi^j_s(x))\right\}
\end{align*}
```
Note that the optimal strategy for employed workers is to engage in random search i.e.: $$\phi_{s}^{j}(x, j') = \frac{1}{\mid\mathcal{J}\mid} \qquad \forall\:x \text{ and }j,j'\in\mathcal{J}$$

thus:

$$J^j_{t}(x,y)=f(x,y,j,z_t)+\beta\mathbb{E}_t\left[(1 - (1-\delta)\lambda^j_{t+1}(x,y))U^j_{t+1}(x) + (1-\delta) \lambda^j_t(x,y)J^j_{t+1}(x,y)\right]$$ {#eq-bellman-match}

## Match Surplus

Define the surplus of a match between a type $x$ worker in location $j$ and a type $y$ firm in location $j'$ as: $$S^{j\to j'}_{t}(x,y) = J^{j}_{t}(x,y) - [U^{j}_t(x) - F^{j\to j'}]$$

After some algebra we obtain the following expression for the surplus of a match: $$S_{t}^{j\to j'}(x,y) = s(x,y,j \to j',z_t) - \Lambda^{j'}(x) - F^{j \to j'} + \beta\mathbb{E}_{t+1}\left[\max\left\{0, S^{j'\to j'}_{t+1}(x,y)\right\}\right]$$ {#eq-surplus}

where $\Lambda^{j'}(x)$ is a function of the expected value of the difference of the instantaneous utility of a type $x$ worker in $j'$ and every other location. Deriviation and function definitions are @sec-appendix_surplus.

Match surplus encodes all the necessary and sufficient conditions for a firm $y'$ in location $j'$ to poach a worker from a firm $y$ in location $j$. note: \begin{align*}
  S_t^{j\to j'}(x,y') - S^{j \to j}_t(x,y') &= J^{j'}_{t}(x,y') - [U^{j}_t(x) - F^{j\to j'}] - \left(J^{j}_{t}(x,y) - [U^{j}_t(x) - F^{j\to j}]\right) \\ 
  &=  J^{j'}_{t}(x,y') - [ J^{j}_{t}(x,y) + F^{j\to j'}]
\end{align*} therefore worker $x$ is poached by firm $y'$ in location $j'$ from firm $y$ in location $j$ if and only if the surplus obtained from moving to $j'$ and matching with $y'$ is higher than the surplus of staying at $j$ matched with $y'$.

When the aggregate state changes from $z_{t-1} \to z_t$ the surplus function determines how does the stock of unemployed and employed workers change: $$u^{j}_{t+}(x) = \underbrace{u^j_t(x)}_{\text{inherited from }t} + \overbrace{\int \Big(\underbrace{\mathbb{1}_{S^{j \to j}_t(x,y)<0}}_{\text{endogenous destruction}} + \underbrace{\delta\mathbb{1}_{S^{j \to j}_t(x,y)\geq0}}_{\text{exogenous destruction}}\Big)h^j_t(x,y)dy}^{\text{new unemployment created by shock}}$$ and $$h^{j}_{t+}(x,y) = (1-\delta)\mathbb{1}_{\left\{S^{j \to j}(x,y)\geq 0\right\}}h^j_t(x,y)$$

## Vacancy Creation

-   $V^j_t(y)$ is the expected value of a type $y$ vacancy making contact with a worker in location $j$. Vacancies are posted in the interim period and meet unemployed and employed type-$x$ workers at a rates $$\frac{u^j_{t+}(x)}{L^j_t} \qquad \text{and} \qquad s\frac{h^j_{t+}(x,y)}{L^j_t}$$ The expected value of posting a vacancy is therefore, the surplus that the posting firm expects to add, potential matches with negative surplus are immediately destroyed therefore those add no surplus. In terms of the Bellman equation we can write:

```{=tex}
\begin{align}
V^j_t(y) &= \underbrace{\sum_{j'\in \mathcal{J}}\left( \int\underbrace{\frac{u^{j'}_{t+}(x)}{L^{j'}_t}}_{\text{likelihhod of match}}\times\overbrace{  S_t^{j'\to j}(x,y)^{+} }^{\text{match survives}}dx\right)}_{\text{expected value added from hiring unemployed workers}} + \ldots\\
&\\
&\ldots +\underbrace{\sum_{j'\in \mathcal{J}}\left(\int \left(\int\underbrace{s\frac{h^{j'}_{t+}(x,y)}{L^{j'}_t}}_{\text{likelihood of match}}\times \overbrace{ [S^{j' \to j}_t(x,y)-S^{j' \to j'}_{t}(x,y')]^{+}}^{\text{poaching is succesfull}}dx\right)dy\right)}_{\text{expected value added from poaching other firms employees}}
\end{align}
```
For simplicity we use the notation $x^+ = \max\{0,x\}$.

Firms will post vacancies such that the marginal cost of the vacancies and the marginal expected benefit $V_t$ are equal: $$c_{j}'(v^{j}_t(y))=q^{j}_{t}V^{j}_{t}(y)$$